{% set name = "portion" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b476d432f0dc0f15ced49720c0b96d755351677250ee107e447c2286134bc81b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python
    - sortedcontainers >=2.2.2,<3

test:
  imports:
    - portion

about:
  home: https://github.com/AlexandreDecan/portion
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Python data structure and operations for intervals

extra:
  recipe-maintainers:
    - AlexandreDecan
    - egemenimre
