{% set name = "portion" %}
{% set version = "2.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4dd6a68bb1cd7a553d9b1f556818708b973c4a8855244e0af79e2586bba5794e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - hatchling
    - python >={{ python_min }}

  run:
    - python >={{ python_min }}
    - sortedcontainers >=2.2.2,<3

test:
  requires:
    - python {{ python_min }}
  imports:
    - portion

about:
  home: https://github.com/AlexandreDecan/portion
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Python data structure and operations for intervals

extra:
  recipe-maintainers:
    - AlexandreDecan
    - egemenimre
